language: node_js
node_js:
  - "17"
install:
  - npm install
script:
  - echo "skipping tests"
before_deploy:
  - npm run lint
  - npm run build
  - cd dist
  - cp ../{package.json,LICENSE,README.md} .
deploy:
  edge: true
  provider: npm
  email: "$email"
  api_key: "$npm_token"
  cleanup: false
  on:
    tags: true
    repo: ymchun/vue-dynamic-form
