language: node_js
version: 1.0
sudo: false
node_js:
  - "12.13"
install:
  - npm install
script:
  - echo "skipping tests"
before_deploy:
  - npm run lint
  - npm run build
deploy:
  edge: true
  provider: npm
  email: "$email"
  api_key: "$npm_token"
  skip_cleanup: true
  on:
    tags: true
    repo: ymchun/vue-dynamic-form
